version: '1.0'
services:
  jupyter-lab:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./tf-yeo:/tf-yeo
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  rabbitmq:
    image: rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
  
  redis:
    image: redis
    restart: unless-stopped
    ports: 
      - 6379:6379